<?php

namespace Heydari81\Media\Models;

use Heydari81\Media\Services\MediaFileService;
use Illuminate\Database\Eloquent\Model;

class Media extends Model
{
protected $casts=[
    'files'=>'json'
];
protected static function booted()
{
    //parent::booted(); // TODO: Change the autogenerated stub
    static::deleting(function ($media){
    MediaFileService::delete($media);
    });
}
}
